### ISSUE TITLE
Doesn't work with Customize UI anymore

### ISSUE THREAD

**Issue by itstommi** [EYHN/vscode-vibrancy#86] opened 2021-02-14 06:58 UTC
This has been a problem for a couple of weeks and I just ignored it because I wasn't using VS Code all that often, but I can't figure out why it doesn't work with Customize UI anymore and it's a little annoying because I loved this plugin.

**Comment by myzenon** [comment] 2021-02-18 18:05
Me too. At first, I try to find out why this extension doesn't work any more. After I disabled the ` Customize UI ` extension, It works. I'm not sure which extension cause this problem. Please find a fix for this. I loved this extension so much.

**Comment by EYHN** [comment] 2021-02-19 03:20
Has been fixed in v1.0.14.

Try the latest version. If the problem is not resolved, please update this issue.

**Closed by EYHN** 2021-02-19 03:20 UTC

**Comment by evolify** [comment] 2021-03-19 09:18
The latest version still has the issue
