### ISSUE TITLE
Not working on M1 Insider edition of VS Code

### ISSUE THREAD

**Issue by MGoeppl** [EYHN/vscode-vibrancy#79] opened 2021-01-18 11:18 UTC
Reloading Vibrancy throws 
```
Command 'Reload Vibrancy' resulted in an error (Running the contributed command: 'extension.updateVibrancy' failed.)
```
as an error and does nothing. 

Edit:
Can be enables when starting app as root using `sudo ~/Downloads/Visual\ Studio\ Code\ -\ Insiders.app/Contents/MacOS/Electron`.

**Comment by BigKunLun** [comment] 2021-01-28 03:50
I'm having the same problem, but it doesn't report an error, it just doesn't work

**Comment by starryloki** [comment] 2021-01-31 05:55
Doesn't work at vscode 1.53.0-insider without error. But it worked in a insider version last month.

**Comment by EYHN** [comment] 2021-02-02 09:32
fixed in v1.0.13, try the latest version. If the problem is not resolved, please update this issue.

**Closed by EYHN** 2021-02-02 09:32 UTC

**Comment by MGoeppl** [comment] 2021-02-02 09:46
Now throws
```
Something went wrong: Error: EROFS: read-only file system, mkdir '/private/var/folders/vv/5ctmmbzd7cl967m52qy0ytx00000gn/T/AppTranslocation/EA274C26-7A4F-4470-9A87-4B1A374F98D6/d/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vscode-vibrancy-runtime-v4'
```
in addition to the old one:
```
Command 'Reload Vibrancy' resulted in an error (Running the contributed command: 'extension.updateVibrancy' failed.)
```
in a popup at the bottom right. 
Also cannot be enabled afterwards. 

My VS Code Info:

```
Version: 1.53.0-insider
Commit: b99487f4168ba70369edfb8629303be0d3979d4b
Date: 2021-02-02T00:13:59.390Z (9 hrs ago)
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin arm64 20.3.0
```

**Comment by EYHN** [comment] 2021-02-02 10:45
@MGoeppl What you see is a new security "feature" in Mac 10.12. If you try to launch an app from the Downloads folder, a "Gatekeeper" moves to and launches the app from a read-only folder. You can move the Vistual Studio Code app bundle into /Applications before launching. This may be able to solve this problem.

**Comment by MGoeppl** [comment] 2021-02-02 10:47
Great, that works. 
Thanks!

**Comment by kotx** [comment] 2022-05-03 02:42
> @mgoeppl What you see is a new security "feature" in Mac 10.12. If you try to launch an app from the Downloads folder, a "Gatekeeper" moves to and launches the app from a read-only folder. You can move the Vistual Studio Code app bundle into /Applications before launching. This may be able to solve this problem.

I had this issue even when VSCode was in Applications, but fixed it with `xattr -d com.apple.quarantine /Applications/Visual\ Studio\ Code.app/`.
