### ISSUE TITLE
Zen mode is black

### ISSUE THREAD

**Issue by tusharsadhwani** [EYHN/vscode-vibrancy#70] opened 2020-10-07 11:30 UTC
Opening Zen mode in vscode (Ctrl+K Z, or Go to View > Appearance > Zen Mode) has a black background

![Regular Window](https://user-images.githubusercontent.com/43412083/95325181-71252400-08be-11eb-85f5-20d4f044059f.png)

![Zen Mode](https://user-images.githubusercontent.com/43412083/95325247-8a2dd500-08be-11eb-86d7-fdb66fddb474.png)

**Comment by EYHN** [comment] 2021-01-26 19:00
In the latest version (v1.0.10) opening Zen mode will automatically restore the default theme style.

I am closing this issue, and if the problem is not resolved you can reopen it.

**Closed by EYHN** 2021-01-26 19:00 UTC
