### ISSUE TITLE
Window Is too big to fit on one monitor.

### ISSUE THREAD

**Issue by Shuna322** [EYHN/vscode-vibrancy#78] opened 2021-01-12 10:09 UTC
![explorer_cvDlXPSbOc](https://user-images.githubusercontent.com/32617699/104299769-47d3ef80-54ce-11eb-812d-5aec0eb553b2.jpg)
![CDUjMKds06](https://user-images.githubusercontent.com/32617699/104299774-49051c80-54ce-11eb-8f69-24c7e5b01709.jpg)

Taskbar transparency app: TaskBarX

Edition	Windows 10 Enterprise
Version	20H2
OS build	19042.685
Experience	Windows Feature Experience Pack 120.2212.551.0

Version: 1.52.1 (user setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by EYHN** [comment] 2021-01-26 19:27
This overflow is caused by the underlying windows implementation. In the latest version (v1.0.10) the acrylic effect has been changed to colorless and transparent so that the overflow is not so obvious.

I am closing this issue, and if the problem is not resolved you can reopen it.

**Closed** 2021-01-26 19:27 UTC
