### ISSUE TITLE
Problem drag, move window by Title Bar

### ISSUE THREAD

**Issue by racoonx2p** [EYHN/vscode-vibrancy#5] opened 2019-07-19 20:47 UTC
Hello,

There seems to be a bug with moving window in Windows 10. After disabling vibrancy and restart VSC moving window works as expected.

![b5IPZOAbeZ](https://user-images.githubusercontent.com/42897550/61564324-83773000-aa76-11e9-8e7e-650f9d5fbcf2.gif)

Btw. Thank you very much for this plugin. I really appreciate it.

**Comment by TTTPOB** [comment] 2019-07-23 06:15
I have run into this problem too

**Comment by syfxlin** [comment] 2019-08-02 04:09
The acrylic effect will have a drag delay on the Electron window. If you use blur behind or transparent gradient, it will not appear.

**Comment by EYHN** [comment] 2019-08-02 04:11
In fact, I have never seen such a problem in windows 10 1809.

**Comment by syfxlin** [comment] 2019-08-02 04:21
This problem occurs in Windows 1903 and I don't know if it only appears in this version. (In fact, some interface errors have appeared in Windows 1903.)

**Comment by mkanet** [comment] 2019-08-03 01:38
I've only tried this on Windows 1903.  Has anyone tried this extension on newer Insider versions of Windows?  Interestingly, this issue doesn't seem to affect GPU or CPU usage.

**Comment by Himself65** [comment] 2019-08-03 03:37
I'm 1903 too and face this problem

**Comment by huyinjie** [comment] 2019-08-03 10:34
Same problem on 1903

**Comment by copperion** [comment] 2019-08-03 11:08
Same problem

**Comment by CircuitLord** [comment] 2019-08-03 21:02
+1

**Comment by gamesgao** [comment] 2019-08-05 06:37
Same problem on 1903

**Comment by AmrBinBashir** [comment] 2019-08-08 13:58
Appears to be 1903 issue as I have no problem on 1809

**Comment by Sominemo** [comment] 2019-08-13 09:33
+1

**Comment by EYHN** [comment] 2019-08-14 11:54
In #14 v1.0.6.  The mouse lag still exists, I have tried many methods, and I can't solve the problem in 1903. 

The problem is not in electron, and there is currently no perfect way to open the acrylic effect without UWP in 1903.

The mouse lag still exists in the latest Windows 10 insider preview.

**Comment by mkanet** [comment] 2019-08-14 14:55
Thanks for taking the time to look into this @EYHN.  I wonder if there's a way to fool Windows into thinking VSCode/Electron is a UWP app.

**Comment by I0F** [comment] 2019-08-16 17:14
I just came here to report this problem. Somewhat glad I'm not the only one having it.

On my pc at work, somewhat decent specs, Windows 1809 - moves with no lag whatsoever.
On my home pc, much better specs, Windows 1903, laggy as hell.

**Comment by EYHN** [comment] 2019-09-07 05:05
Many days have passed and this problem still there.
I have push the native code for windows at https://github.com/EYHN/vscode-vibrancy/tree/master/src/blur-cli .
Maybe you can help me if you know very well about windows

**Comment by EYHN** [comment] 2019-10-18 04:26
news: In window 10 1903, I found that reducing the "mouse rate" below the frame Rate can effectively solve this problem.

**Comment by EYHN** [comment] 2019-10-26 10:49
I spent a few days researching this problem, and now I give up. It seems to be a problem inside DWM, the mouse polling rate is higher than the screen rate, causing the rendering request to block in the queue, and it looks like a mouse delay.

Don't worry, the same problem also appears in the Microsoft Office, thousands of Windows users are troubled by it, the following are some discussion:

https://answers.microsoft.com/en-us/msoffice/forum/all/why-does-my-excel-window-lag-so-much-when-moved/04b1fb97-b9da-481e-b37a-63257460c5b7

https://answers.microsoft.com/en-us/windows/forum/windows_10-performance/windows-10-mouse-lag-sluggish-window-dragging-in/12ab88a5-9e13-4d37-8f2d-106d56fcd775

There are now some methods:

- **Use Windows 10 1809 and wait for Microsoft to fix the problem**
- **Close 'Show window contents while dragging'**
In the search box on the taskbar, type 'performance', then select 'Adjust the appearance and performance of Windows' in the list of results. On the 'Visual Effects' tab, Un-selecting 'Show window contents while dragging'.
- Reduce mouse polling rate
In many gaming mouse driver panels can adjust the mouse polling rate.

  I will also provide a transparent version only, removing blur and compatibility with all operating systems and environments.

**Comment by quank123wip** [comment] 2020-02-18 01:12
@EYHN I think I found a solution.
In another electron app Terminus, they provide a setting "background type", and two type "Blur" and "Fluent", it calls a function ```this.electron.ipcRenderer.send('window-set-vibrancy', enable, type)```, and I found that "Fluent" works lag but "Blur" works well. I don't know how ```this.electron.ipcRenderer.send('window-set-vibrancy', enable, type)``` works, but I think this is a solution before MS fix it in DWM.

**Comment by huhuime** [comment] 2020-02-28 09:04
我安装了[Aero Glass](https://glass8.eu/guide)后在改对win10处理的代码让其调用dwm（即win7实现）部分运行在win10 1909拖动时窗口不会卡顿

**Comment by slacksoft** [comment] 2020-03-06 03:34
> 我安装了[Aero Glass](https://glass8.eu/guide)后在改对win10处理的代码让其调用dwm（即win7实现）部分运行在win10 1909时时窗口不会卡顿

然而Aero Glass在win10 2004里不起作用

**Comment by huhuime** [comment] 2020-03-10 02:37
> > 我安装了[Aero Glass](https://glass8.eu/guide)后在改对win10处理的代码让其调用dwm（即win7实现）部分运行在win10 1909时时窗口不会卡顿
> 
> 然而Aero Glass在win10 2004里不起作用

从win10通用开发的调试包里取文件覆盖然后命令重建symbols也不行？

**Comment by Toby56** [comment] 2020-03-12 02:39
Another way is to put windows into power saving mode, which usually disables all transparency effects, but for some reason it fixes the lag 🤷‍♂️

**Comment by reycn** [comment] 2020-03-16 08:59
似乎 Win 10 2004 版本 KB4541738 修复了此项问题。

**Comment by 1470391328** [comment] 2020-03-16 14:17
你能提供详细结局办法吗，windows1909 还是有拖动延迟

**Comment by reycn** [comment] 2020-03-16 16:54
奇怪，我之前运行 unpacked 都是正常的无延迟拖动，但现在又有延迟了……

> 似乎 Win 10 2004 版本 KB4541738 修复了此项问题。

**Comment by 1470391328** [comment] 2020-03-16 17:19
😂awsome

**Comment by huhuime** [comment] 2020-03-17 03:27
> 你能提供详细解决办法吗，windows1909 还是有拖动延迟

1909直接用[Aero Glass](https://glass8.eu/guide)不行么？ps：需要修改该扩展代码

**Comment by 1470391328** [comment] 2020-03-17 05:30
既然推动有bug，能否通过提供毛玻璃特效的透明背景图片代替解决

**Comment by doublethinkio** [comment] 2020-04-06 03:17
Use [](https://www.autohotkey.com/docs/scripts/EasyWindowDrag_ (KDE). HTM) to move window can relieve this problem

**Comment by Spenhouet** [comment] 2020-05-20 09:45
For me dragging the window got impossible with this extension installed. The window is moving in slow motion. It is not a CPU/GPU resource problem.

This made VS code unusable. I had to uninstall this extension to use VS code again.

**Comment by Toby56** [comment] 2020-05-20 11:42
@Spenhouet Thank you for reminding us what this bug is. It's a Windows problem that comes as a result of using the Acrylic effect in such an unsupported way, and there aren't really any good solutions.

**Comment by Spenhouet** [comment] 2020-05-20 11:45
@Toby56 I was not sure if it is the same issue as OP described. It looks nothing like in the GIF he provided.

**Comment by Toby56** [comment] 2020-05-20 23:38
@Spenhouet Yeah, the GIF isn't very clear, but it is as you described! It's a mouse polling issue, where as soon is you start dragging, the window goes slower than it should, and accumulates a massive delay between where it is and where it should be. Unfortunately, there is nothing you can do about it :(

**Comment by iPyGuy** [comment] 2020-05-30 02:39
So is this still an issue as of the latest Win10 releases? Don't want to install this if it will essentially break VSCode for me...

**Comment by Toby56** [comment] 2020-05-30 02:41
@iPyGuy Yeah basically, don't expect it to be fixed any time soon. It's not an official windows method.

**Comment by huhuime** [comment] 2020-06-16 07:45
> 似乎 Win 10 2004 版本 KB4541738 修复了此项问题。

这个补丁没有合并到正式的2004里面也没有发布到半年频道里吧

**Comment by jonaskuske** [comment] 2020-06-19 22:58
@EYHN @Toby56
Do you think this could be "fixed" by disabling the acrylic effect while the window is moved, as you (@Toby56) described here: https://github.com/23phy/ewc/issues/22#issuecomment-599448590 ?

Alternatively, do you think it'd be possible to disable "Show windows contents while dragging" in performance settings only while VSCode is active/moved, by changing the related registry entry on the fly, on focus or move event? Not seeing window contents for all windows is pretty bad, but if that only affected VSCode I could live with the tradeoff 😅

**Comment by Toby56** [comment] 2020-06-19 23:54
@jonaskuske 
Disabling the acrylic affect on drag probably is the best internal fix. It can be a but fiddly, but you can switch it to just transparency without any blur. Another factor that makes it more complicated, is that the acrylic breaks when enabling it from another blur effect in battery saver mode because acrylic is usually disabled in that mode? I can't remember. Because of this you have to reset the blur each time which can create a small white flash. There's no way to tell if it's in battery saver mode or not as far as I know and battery save wouldn't be very common. idk.

But it works for the most part and would be MUCH MUCH better than messing with the registry on the fly. For sure I don't think that doing that is practical.

**Comment by jonaskuske** [comment] 2020-06-20 02:43
@Toby56 

> the acrylic breaks when enabling it from another blur effect in battery saver mode because acrylic is usually disabled in that mode?

Yeah, Acrylic is usually disabled both in Energy Saver Mode and while a window isn't focused. So there usually is only one window with acrylic effects active, while the ones in the background display opaque.

> There's no way to tell if it's in battery saver mode or not as far as I know and battery save wouldn't be very common. idk.

For me it is automatically enabled once I hit 20% battery, so I wouldn't say it's uncommon. But you can detect it!
It's possibe with the [node bindings for the native Windows Runtime API](https://github.com/NodeRT/NodeRT):

```js
const { PowerManager } = require('@nodert-win10-rs4/windows.system.power')

let energySaverEnabled = PowerManager.energySaverStatus === 2

PowerManager.on('energySaverStatusChanged', () => {
  energySaverEnabled = PowerManager.energySaverStatus === 2
})
```

**Comment by Toby56** [comment] 2020-06-20 04:19
@jonaskuske 
That's great that you know a way to detect battery saver mode using NodeJS bindings to native Windows functions! That looks like a super simple way to solve some problems. This way we can write code that switches to "blur behind" usually, and to plain transparency on battery saver mode, eliminating the unnecessary white flash.

For this specific problem, I don't know how the code in this project is structured, will have to ask @EYHN if they want to implement something like this. Maybe I'll post a GIF of it in action.

**Comment by jonaskuske** [comment] 2020-06-20 04:38
@Toby56 
I just realized that native dependencies are probably not an option in VSCode extensions, so while this solution should help everyone who wants to add the acrylic effect to their *own* Electron app (so they can compile it against their specific Electron/Node version), I don't know if it helps here :/

 Would probably need to ship a separate pre-built binary instead of using the Node bindings, as this repository is already doing with `blur-cli.exe` 🤔

**Comment by Toby56** [comment] 2020-06-20 04:51
@jonaskuske 
That's true! Didn't think of that. I have no idea how, but it could probably be build in to the C++ part that is compiled into the binary??? I really don't know the limitations of VSCode extensions.

Definitely useful for my own app tho 😀!

**Comment by jonaskuske** [comment] 2020-06-20 14:37
Right, that should probably work. Unfortunately I don't really know anything about C++ either (other than the little that is needed to program Arduinos) :/

Anyway if this is implemented it should definitely be optional, as folks with e.g. 144Hz monitors *can* have vibrancy during window movement if they set their mouse sample rate to something like 125, which should still be fast enough for everyday use.

**Comment by Jinhaihan** [comment] 2020-06-24 05:33
@quank123wip  @EYHN 
Yes, I found it too.
Acrylic background in terminus have two options:
![image](https://user-images.githubusercontent.com/25563920/85504683-1291ae00-b61f-11ea-9a9f-c614618d3f28.png)

Blur have no problem, And Fluent have lag issue too.

So I think this is the answer.

**Comment by Spenhouet** [comment] 2020-06-24 05:54
No sure if that is of any help but the Window Terminal has a working transparency effect. They call it "Acrylic".
The Terminal does not build on electron... it is implemented in C++.

![image](https://user-images.githubusercontent.com/7819068/85505757-52d93800-b5ef-11ea-9a34-7f3284c34dba.png)

You can also change the opacity:

![image](https://user-images.githubusercontent.com/7819068/85505867-92078900-b5ef-11ea-8e05-9e0793957e58.png)

Maybe looking at there implementation can help:

https://github.com/microsoft/terminal/blob/master/src/cascadia/TerminalControl/TermControl.cpp#L376

**Comment by Toby56** [comment] 2020-06-24 06:17
@Spenhouet Yeah, sorry but that doesn't really help us much. The open source Windows Terminal as well as many many other apps use this effect (always called acrylic), but they are dedicated windows apps and can do the "official" way, which will work out-of-the-box. However what we are doing, is putting something where it really was never intended to go, which is why it has bugs that won't be fixed

**Comment by Toby56** [comment] 2020-06-24 06:22
@Jinhaihan Yes, true, we can just make it blur like that, and it doesn't have the problem! Maybe we should. But imo it doesn't look nearly as nice as the "fluent" acrylic effect. I think it's an old effect used in Windows 7 (Aero), or something like that. The blur radius is not as much, and it doesn't have the fluent Windows 10 "acrylic" texture, as well as the other layers that go into making the acrylic blur look nice.

Having an option like Terminus does is perfectly possible, and maybe a solution many would be happy with.

**Comment by Spenhouet** [comment] 2020-06-24 08:34
@Toby56 That might be a dumm question: Is it impossible to go the "official" way?

**Comment by Toby56** [comment] 2020-06-24 10:26
@Spenhouet Maybe, if you feel like rewriting VS Code from the ground up. Otherwise, probably not.

I don't actually know a whole lot about how the acrylic effect is applied to a chromium window using Node JS and C++. But VS Code is and will always be made in Electron, and there is no officially supported way of doing this. I'm pretty amazed that this method works at all. So unless some genius finds another way, then we're stuck like this.

**Comment by Spenhouet** [comment] 2020-06-24 10:52
@Toby56 Okay, makes sense.

I guess the acrylic effect will be more present in Windows in the future. VS code will probably adopt that in this distant future.

**Comment by jonaskuske** [comment] 2020-06-24 15:06
@Spenhouet 
Yep, currently the Acrylic effect is a feature of XAML, the UI framework that only modern Windows apps (the type you typically see in the Microsoft Store) can use. That's why it's no problem for Windows Terminal and others. "Old-school" applications can use most of the modern APIs, but not those that rely on rendering, views etc.
I don't know either how the hack in this repo actually works, but it's definitely a hack 😃

However, with the upcoming WinUI 3 (part of [Project Reunion](https://github.com/microsoft/ProjectReunion), Microsoft's attempt to unify old and modern APIs) we'll get a feature called "XAML Islands", which allows usage of modern UI in traditional applications. Then it should be possible to add Acrylic without hacks, maybe even as direct feature of Electron itself. 🙏🏻

**Comment by Toby56** [comment] 2020-06-24 22:18
@jonaskuske Wow that's pretty cool, didn't know Microsoft were planning something like this!!! Some things like tray icons are not possible for UWP apps without packaging a companion Win32 application.

**Comment by LegoLivesMatter** [comment] 2020-07-04 16:04
I am glad to report that Windows 10 Insider Preview (build 20161) fixed the issue for me.

**Comment by Toby56** [comment] 2020-07-04 16:09
@LegoLivesMatter That's fantastic to hear! I should move to the fast insider channel to verify this.

**Comment by LegoLivesMatter** [comment] 2020-07-04 16:11
@Toby56 Good luck!

**Comment by Toby56** [comment] 2020-07-06 10:35
@jonaskuske @LegoLivesMatter @racoonx2p @EYHN 

I can confirm that it is fixed in build 20161!
Well *mostly*...

I say **mostly** because, while it is great and **completely usable** now, it is a tiny bit quirky. **Resizing still has this issue** for me, which is annoying, but probably not an issue for anyone, unless you find yourself resizing a lot. Short quick resizes is fine.

<details>
  <summary>Something that I noticed that's not really related...</summary>
Something that I noticed that's not really related, and I don't know if this is a new issue or not, is that the blur and colour-filtering elements of the acrylic effect can disappear sometimes for certain reasons on my dual-display setup. If the window is dragged between displays, so that it is on both at the same time, the effect will only render properly on one of the displays, on the other it'll just be dark transparent with the texture (which doesn't look too bad). Sometimes it can flicker a lot. I can't capture it in a screenshot. It can also break this way temporarily at other random times. It's okay because it only happens under certain conditions, but it's weird.
</details>

Boy, does it look good tho:
![image](https://user-images.githubusercontent.com/20509848/86583330-6a88c700-bfc6-11ea-96a7-a8b30f430187.png)

**Comment by LegoLivesMatter** [comment] 2020-07-06 10:56
I have dual monitors, and the same issue too. Also, if the window is close to an edge of any of the monitors, a small part of that edge becomes translucent without blur. Still better than nothing!

**Comment by LegoLivesMatter** [comment] 2020-07-06 13:36
I have also noticed that when the VS Code window is maximized on the secondary monitor, the blur disappears but the acrylic "filter" stays there. From what I can tell this is a consequence of the window slightly "reaching" the other monitor. This doesn't happen when the VS Code window isn't focused or when it's maximized on the primary monitor.

**Comment by Toby56** [comment] 2020-07-06 14:00
@LegoLivesMatter Yeah I had this problem too, forgot to mention it. So stupid, but windows often reach into the next monitor, and this is obviously the cause. Cross our fingers and maybe it'll get fixed. Hopefully both the effect breaking and window crossing!

**Comment by xenobrain** [comment] 2020-07-09 17:13
For some reason using a theme with Stardock WindowBlinds actually resolves this issue as well.  It must be doing something with window manager compositing but no idea what.  There's a quick flicker when maximizing the window but otherwise it's good.

**Comment by VS-ux** [comment] 2020-07-24 19:59
I installed windows-insider dev-channel, and the dragging is fine. However, resizing still poses issues. I've also noticed the my 64 bit winforms-app using this method has this issue, but not the 32 bit version. Also, I have a WPF test app that is 32 & 64 bit while using `SetWindowCompositionAttribute`, and it resizes OK. Also, Avalonia resizes OK.

**Comment by doublethinkio** [comment] 2020-07-25 01:26
Use https://lexikos.github.io/v2/docs/scripts/#EasyWindowDrag_ (KDE) can alleviate this problem

**Comment by VS-ux** [comment] 2020-07-25 22:37
Thanks for your reply, but I stated that I didn't have issues with dragging (ie. moving the window) on the insider-dev channel, but had issues resizing on 64-bit app.

**Comment by tims-j** [comment] 2020-09-30 22:51
@doublethinkio I'm on windows 10 build 19042.541 and still have the issue?

**Comment by ziggythehamster** [comment] 2020-10-19 19:31
20H2 build 19042.572 here and also it still happens, so I think something that @doublethinkio has going specifically has made it work correctly. For me, dragging works and is smooth, it's just very very slow. That's different from some people where it's both slow and not smooth.

**Comment by ziggythehamster** [comment] 2020-10-19 19:58
@Jinhaihan mentioned that Blur works for them in Terminus and Fluent has the same issue in [this comment](https://github.com/EYHN/vscode-vibrancy/issues/5#issuecomment-648599635). I did like 5 minutes of research and it appears that "Blur" maps to option 3, called `ACCENT_ENABLE_BLURBEHIND` in this project's `blur-cli` and "Fluent" maps to option 4, called `ACCENT_ENABLE_ACRYLIC` in `blur-cli`. This isn't configurable, and instead `ACCENT_ENABLE_ACRYLIC` (actually called `ACCENT_ENABLE_ACRYLICBLURBEHIND` in the API) is always chosen.

Making this configurable would be pretty trivial, but I don't have a Visual C++ toolchain set up to be able to build a new blur-cli.

**Comment by 2360702390** [comment] 2020-11-20 12:16
怎么删除毛玻璃效果，我卸载插件，删除配置。  还是没用

**Comment by mkanet** [comment] 2020-12-13 03:44
@doublethinkio, thanks for providing a workaround.  I tried executing **EasyWindowDrag.ahk** with **autohotkey.exe**.  Unfortunately, I get the below error.  I don't have any issues executing other AutoHotkey scripts.

![Screenshot](https://user-images.githubusercontent.com/811008/102002483-d8da5f80-3cb1-11eb-9c40-fafaf8877860.png)

Even if I use the original script I downloaded directly from:
https://lexikos.github.io/v2/docs/scripts/EasyWindowDrag.ahk

> Use EasyWindowDrag(KDE style).ahk can alleviate this problem
> 
> https://www.autohotkey.com/
> https://lexikos.github.io/v2/docs/scripts/
> 
> ```ahk
> ; Easy Window Dragging -- KDE style (based on the v1 script by Jonny) 
> ; https://www.autohotkey.com
> ; This script makes it much easier to move or resize a window: 1) Hold down
> ; the ALT key and LEFT-click anywhere inside a window to drag it to a new
> ; location; 2) Hold down ALT and RIGHT-click-drag anywhere inside a window
> ; to easily resize it; 3) Press ALT twice, but before releasing it the second
> ```

**Comment by lemonnuggets** [comment] 2021-01-16 09:10
Not really sure if this helps but here's a project that looks like it might help with the problem.
[Seo-Rii/electron-acrylic-window](https://github.com/Seo-Rii/electron-acrylic-window)

**Comment by lonelyion** [comment] 2021-01-26 12:35
I found that setting the backgroud of Terminus ([eugeny/terminus](github.com/eugeny/terminus) 1.0.127) into Fluent, it will set the background as non-transparent when dragging the window. After stoping or temporarily staying, the window restore fluent background. The lag will not appear.

Maybe this is a good workaround for the project.

**Comment by EYHN** [comment] 2021-01-26 19:02
The latest version (v1.0.10) contains a solution to the mouse lag, [please see here for details](https://github.com/EYHN/vscode-vibrancy/discussions/80).

**Closed** 2021-01-26 19:02 UTC

**Comment by mkanet** [comment] 2021-01-26 21:26
Thank you for your effort.  I tried the new solution on 2 of my PCs.  It didn't seem to make much difference on my PC#1 (with 2560x1440 @60hz ) or PC#2 ( 1980x1080 @60Hz ); even with a relatively fast PC with fast video card.  Lag is about the same for me.
