### ISSUE TITLE
Could not work well with other background-change extensions.

### ISSUE THREAD

**Issue by slanterns** [EYHN/vscode-vibrancy#7] opened 2019-08-03 21:21 UTC
Hi, I thried to use it with [background-cover](https://github.com/shalldie/vscode-background), an extension to add global background to vsc. However, it cannot work after I installed vibrancy.
Since the function of these two extensions are complemented, I think it would be better to let them work together.
Thanks!

**Comment by EYHN** [comment] 2019-08-07 22:32
I use both background and vibrancy. They work together.
![image](https://user-images.githubusercontent.com/13579374/62662332-ae3a1180-b9ae-11e9-9b26-bdce5c525d57.png)

**Comment by EYHN** [comment] 2019-08-07 22:38
I am closing this issue, and if the problem is not resolved you can reopen it.

**Closed** 2019-08-07 22:38 UTC
