### ISSUE TITLE
Vibrancy effect not shown in fullscreen mode

### ISSUE THREAD

**Issue by bogdan-calapod** [EYHN/vscode-vibrancy#12] opened 2019-08-12 08:45 UTC
When enabling fullscreen mode, the vibrancy effect is completely disabled:

![image](https://user-images.githubusercontent.com/5462727/62853938-89b79f80-bcf6-11e9-9a6a-463aba055414.png)

When in maximized, fullscreen mode it works perfectly:

![image](https://user-images.githubusercontent.com/5462727/62853970-9936e880-bcf6-11e9-9f83-c2ce18439af3.png)

**Comment by EYHN** [comment] 2021-01-26 19:04
In the latest version (v1.0.10) opening fullscreen mode will automatically restore the default theme style.

I am closing this issue, and if the problem is not resolved you can reopen it.

**Closed by EYHN** 2021-01-26 19:04 UTC
