### ISSUE TITLE
多屏幕时候，最大化溢出

### ISSUE THREAD

**Issue by DotWho** [EYHN/vscode-vibrancy#11] opened 2019-08-12 05:59 UTC
我现在2个显示屏，用了vibrancy后，第二个屏幕把vscode最大化后，第一个屏幕可以看见vscode的一条边。
如下图所示：
![image](https://user-images.githubusercontent.com/35942318/62847544-6d712e00-bd09-11e9-8c68-68667a2042e7.png)

**Comment by EYHN** [comment] 2021-01-26 18:58
This overflow is caused by the underlying windows implementation. In the latest version (v1.0.10) the acrylic effect has been changed to colorless and transparent so that the overflow is not so obvious.

I am closing this issue, and if the problem is not resolved you can reopen it.

**Closed by EYHN** 2021-01-26 18:58 UTC
